### PR TITLE
Make use of new ACME certmanager package.

### PR DESCRIPTION
**Pull request by rgooch**

### CODE REVIEW

**Comment by cviecco** [comment]
LGTM, but needs documentation

**Comment by rgooch** [comment]
There already is a sample configuration. I think that came in with one of the GitDB changes. See: https://github.com/Cloud-Foundations/keymaster/blob/master/docs/examples/keymasterd/aws-config.yml

**Comment by cviecco** [comment]
the example is incomplete (I think) I think you are missing the target urls?

**Comment by rgooch** [comment]
The default is taken from `host_identity`. If you specify something, it will override that.

**Pull request merged**
